on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.17
      - name: cdk deploy
        uses: arnaskro/aws-cdk-v2-github-actions@v2.3.0
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: 'cdk-notif'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


#      - name: Deploy                       
#        uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.1.3
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#        with:
#          cdk_action: 'deploy --verbose --require-approval never'          
#          cdk_stack: 'CdkStack-Test-Ed'
#          cdk_stack_directory: 'cdk-notif'
          
#      - name: cdk deploy
#        uses: youyo/aws-cdk-github-actions@v2
#        with:
#          cdk_subcommand: 'deploy'
#          cdk_stack: 'CdkStack-Test-Ed'
#          cdk_args: '--require-approval never'
#          actions_comment: false,
#          working_dir: 'cdk-notif'
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

#      - name: Deploy
#        uses: udondan/cdk-nodejs@v0.4.0
#        with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
