on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          #role-to-assume: arn:aws:iam::861267531349:role/github-role
          #role-session-name: sampelrolesession
      - name: Install NPM
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk' 
      - name: Node Version
        run: node -v
      - name: Npm Version
        run: npm -v
      - name: Install project dependecies
        run: cd cdk-notif && npm i
      - name: CDK Synth
        run: cd cdk-notif && npm run cdk synth -v -o
      - name: CDK Deploy
        run: cd cdk-notif && npm run cdk deploy --all --require-approval never

#      - uses: actions/setup-node@v3
#        with:
#          node-version: "16"
#      - name: Install CDK, Typescript and Ts-Node
#        run: |        
#          npm install -g typescript
#          npm install -g ts-node
#          npm install -g aws-cdk
#      - name: Configure aws credentials
#        uses: aws-actions/configure-aws-credentials@master
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#      - name: Github_Workspace
#        run: echo ${GITHUB_WORKSPACE} 
#      - name: Test List
#        run: ls
#      - name: Install dependecies
#        run: cd cdk-notif && npm i
##        run: yarn
#      - name: Synth stack
#        run: cd cdk-notif && cdk synth
#        # run: cd cdk-notif && yarn cdk synth
#      - name: Deploy stack
#        run: cd cdk-notif && yarn cdk deploy --all --require-approval never

      
#      - name: cdk deploy
#        uses: arnaskro/aws-cdk-v2-github-actions@v2.3.0
#        with:
#          cdk_subcommand: 'deploy'
#          cdk_args: '--require-approval never'
#          actions_comment: false
#          working_dir: 'cdk-notif'
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

#      - name: Deploy                       
#        uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.1.3
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#        with:
#          cdk_action: 'deploy --verbose --require-approval never'          
#          cdk_stack: 'CdkStack-Test-Ed'
#          cdk_stack_directory: 'cdk-notif'
          
#      - name: cdk deploy
#        uses: youyo/aws-cdk-github-actions@v2
#        with:
#          cdk_subcommand: 'deploy'
#          cdk_stack: 'CdkStack-Test-Ed'
#          cdk_args: '--require-approval never'
#          actions_comment: false,
#          working_dir: 'cdk-notif'
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

#      - name: Deploy
#        uses: udondan/cdk-nodejs@v0.4.0
#        with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
